### ISSUE TITLE
Sugestões

### ISSUE THREAD

**Issue by Marlysson** [Gabriel-Brito/Learning-FrontEnd#4]
- Coloca um screenshot do projeto (ou de cada um) ai fica fácil pra comunidade ver.
- Tem uns artigos do FreeCodeCamp que tem várias dicas assim, é o : FrontEnd Hero. Muito boas por sinal , estou tentando seguir elas, tem uns desafios legais.

**Comment by gabriel-brito** [comment]
Valeu pelas dicas! Vou dar uma olhada lá!
